language: csharp
solution: lcmsNET.sln
mono: none
dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install -y liblcms2-2
dotnet: 2.1.811
script:
  - dotnet restore
  - dotnet test
